---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

# Instale os pacotes: install.packages("dplyr", "ggplot2")
```{r setup}
library(dplyr)
library(ggplot2)
```

```{r}
z_f <- function(confianca) {
  qnorm(1 - (1 - confianca)/2)
}

n_f <- function(z, desvio_padrao, margem_erro, media) {
  ((100 * z * desvio_padrao) / (margem_erro * media))^2
}

ic_erro_f <- function(z, desvio_padrao, tamanho_amostra) {
  z * (desvio_padrao / sqrt(tamanho_amostra))
}
```

```{r}
arquivos <- c("quick_193_80M.txt_filt", "merge_45_80M.txt_filt", "counting_45_80M.txt_filt")

dados <- data.frame()
for (arquivo in arquivos) {
  dados <- rbind(dados, data.frame(arquivo, time = read.table(arquivo)[,1]))
}
```

```{r}
dados %>%
  group_by(arquivo) %>%
  summarise(media_ping = mean(time))

ggplot(dados, aes(x = arquivo, y = time, col = arquivo)) +
  geom_jitter(height = 0)
```


```{r}
res <- dados %>%
       group_by(arquivo) %>%
       summarise(media = mean(time),
                 desvio_padrao = sd(time),
                 tamanho_amostra = n(),
                 z = z_f(.95),
                 ic_erro = ic_erro_f(z, desvio_padrao, tamanho_amostra),
                 ic_menor = media - ic_erro,
                 ic_maior = media + ic_erro,
                 n_ideal = n_f(z, desvio_padrao, margem_erro = time, media))
res

ggplot(res, aes(x = arquivo, y = media)) +
  geom_errorbar(aes(ymin = ic_menor, ymax = ic_maior)) +
  geom_point()
```



